# Generated by Django 4.2.17 on 2025-01-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('full_time_result', models.CharField(max_length=1)),
                ('half_time_result', models.CharField(max_length=1)),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('home_yellow_cards', models.IntegerField(default=0)),
                ('away_yellow_cards', models.IntegerField(default=0)),
                ('home_red_cards', models.IntegerField(default=0)),
                ('away_red_cards', models.IntegerField(default=0)),
                ('season', models.CharField(max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league_app.team')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league_app.referee')),
            ],
        ),
    ]
